repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: fix-encoding-pragma
- repo: https://github.com/psf/black
  rev: 23.12.1
  hooks:
    - id: black
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.10.0  # Use the ref you want to point at
  hooks:
    - id: python-use-type-annotations
    - id: python-no-log-warn
    - id: python-no-eval
- repo: https://github.com/zricethezav/gitleaks
  rev: v8.18.1
  hooks:
    - id: gitleaks
- repo: https://github.com/gitguardian/ggshield
  rev: v1.23.0
  hooks:
    - id: ggshield
      language_version: python3
      stages: [commit]
- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: pylint
      additional_dependencies: ["ruia", "peewee-async", "aiomysql", "aiopg"]
      language: python_venv
      types: [python]
      args:
        [
          "-rn", # Only display messages
          "-sn", # Don't display the score
          "--rcfile=.pylintrc", # Link to your config file
          "--load-plugins=pylint.extensions.docparams", # Load an extension
        ]
ci:
    autofix_commit_msg: |
        [pre-commit.ci] auto fixes from pre-commit.com hooks

        for more information, see https://pre-commit.ci
    autofix_prs: true
    autoupdate_branch: ''
    autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
    autoupdate_schedule: weekly
    skip: [pylint, ggshield]
    submodules: true
