name: Semantic Release

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Codecov
    branches:
      - main
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        name: Setup Python
        with:
          python-version: 3.7.9
          cache: poetry
      - run: |
          poetry install && poetry install -E aiomysql -E aiopg
      - name: Python Semantic Release
        uses: relekang/python-semantic-release@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository_username: __token__
          repository_password: ${{ secrets.PYPI_TOKEN }}
